x-postgres-environment: &postgres-environment
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

x-django-environment: &django-environment
  DJANGO_DEBUG: ${DJANGO_DEBUG:-false}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

x-mail-environment: &mail-environment
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  EMAIL_USE_TLS: ${EMAIL_USE_TLS}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_HOST_USER: ${EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}

x-ai-environment: &ai-environment
  OPENAI_API_KEY: ${OPENAI_API_KEY}

services:
  backend:

    image: registry.gitlab.com/my_website7155632/nomi-lang:latest
    command: "sh /scripts/prod.sh"
    networks:
      - web
    environment:
      <<:
        - *django-environment
        - *postgres-environment
        - *mail-environment
        - *ai-environment
    depends_on:
      - postgres

    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - frontend_build:/frontend/dist

  postgres:
    image: postgres:latest
    networks:
      - web
    environment:
      <<:
        - *postgres-environment
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    depends_on:
      - backend

    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - frontend_build:/frontend_build
      - ./nginx:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres_data:
  static_files:
  media_files:
  frontend_build:

networks:
  web:
    external: true





