x-postgres-environment: &postgres-environment
  POSTGRES_DB:
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_USER:
  POSTGRES_PASSWORD:

x-django-environment: &django-environment
  DJANGO_DEBUG:
  DJANGO_SECRET_KEY:

x-mail-environment: &mail-environment
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  EMAIL_USE_TLS: ${EMAIL_USE_TLS}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_HOST_USER: ${EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}

x-ai-environment: &ai-environment
  OPENAI_API_KEY:

services:
  backend-cookbook:

    image: registry.gitlab.com/my_website7155632/nomi-lang:latest
    command: "sh /scripts/prod.sh"
    environment:
      <<:
        - *django-environment
        - *postgres-environment
        - *mail-environment
        - *ai-environment
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - cookbook_build:/cookbook/dist
      - main_build:/main/dist

  postgres:
    image: postgres:latest
    environment:
      <<:
        - *postgres-environment
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - cookbook_build:/cookbook_build
      - main_build:/main_build
      - ./nginx:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres_data:
  static_files:
  media_files:
  cookbook_build:
  main_build:





