# Generated by Django 5.2.3 on 2025-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
