# Generated by Django 5.2.3 on 2025-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar2',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/'),
        ),
    ]
