# Generated by Django 5.2.3 on 2025-08-28 16:48

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_images/', validators=[utils.validators.MaxFileSizeValidator(max_mb=1.5)])),
                ('image2', models.ImageField(blank=True, null=True, upload_to='section_images/', validators=[utils.validators.MaxFileSizeValidator(max_mb=1.5)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='category.category')),
            ],
        ),
    ]
