# Generated by Django 5.2.3 on 2025-08-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='showcase.project'),
        ),
    ]
