# Generated by Django 5.2.3 on 2025-08-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
    ]
