# Generated by Django 5.2.3 on 2025-08-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_section_image2'),
        ('showcase', '0002_remove_project_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='showcase.project'),
        ),
    ]
