# Generated by Django 5.2.3 on 2025-09-15 22:49

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', validators=[utils.validators.MaxFileSizeValidator(max_mb=5.0)])),
                ('view', models.URLField(blank=True, max_length=500)),
                ('view_code', models.URLField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='category.category')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='section.section')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
