name: cookbook
dependencies:
  - python==3.13.5
  - pip==25.1
  - psycopg2
  - pip:
      - django==5.2.3
      - django-cors-headers==4.7.0
      - djangorestframework==3.16.0
      - djangorestframework_simplejwt==5.5.0
      - drf-yasg==1.21.10
      - pillow==11.3.0
      - flake8==7.3.0
      - gunicorn==23.0.0
      - openai==1.93.3
      - requests