# Generated by Django 5.2.3 on 2025-07-08 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('customUser', '0002_customuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
