# Generated by Django 5.2.3 on 2025-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cookbook_images/'),
        ),
    ]
