# Generated by Django 5.2.3 on 2025-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0002_cookbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
