# Generated by Django 5.2.3 on 2025-07-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cookbook_images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
